name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Log in to GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Step 3: Build the Docker image
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/peach_application_poc:latest

    # Step 4: Push the Docker image to GHCR
    - name: Push Docker Image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/peach_application_poc:latest
